on:
  pull_request: 
    types: 
     - opened

jobs:
    testing-action:
        runs-on: ubuntu-latest
        permissions: 
            issues: write
            pull-requests: write
        
        steps:
        - name: Post PR Comment
          uses: srikanth240695/docker-actions-pr-giphy-comment@main
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            giphy-api-key: ${{ secrets.GIPHY_API_KEY }}

        - name: Post Javascript Action PR Comment
          uses: srikanth240695/js-action-pr-giphy-comment@1.0.3-alpha
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            giphy-api-key: ${{ secrets.GIPHY_API_KEY }}
